# Name of your application. Used to uniquely configure containers.
service: gberlati

# Name of the container image.
image: gberlati/eazylinks

# Deploy to these servers.
servers:
  web:
    hosts:
      - 174.138.90.187

# Credentials for your image host.
registry:
  username: gberlati
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

traefik:
  options:
    publish:
      - "443:443"
  args:
    entryPoints.websecure.address: ":443"

volumes:
  - "storage:/rails/storage"
